### ISSUE TITLE
Getting error when reading card

### ISSUE THREAD

**Issue by ClausMunch** [Olaii/node-acr1222l#1]
Hi,

I'm getting this error when trying to read the UUID:
[ACR1222L]Read UUID requested.
[ACR1222L]Connect requested with SHARE_MODE=2 and PROTOCOL=3
[ACR1222L]Error connecting with reader: Error: SCardConnect error: The specified reader is not currently available for use.
(0x80100017)
(node:17900) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: SCardConnect error: The specified reader is not currently available for use.
(0x80100017)
(node:17900) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ACR1222L]Card removed

Any idea on whats wrong? (I'm a total node novice)

**Comment by boris-savic** [comment]
Hello,

can you please provide the following information:
1. Library version
2. Operating system
3. Do you have ACR1222L device drivers installed?
4. Have you tried the examples that are attached or is this happening with custom script?

Thanks

**Comment by ClausMunch** [comment]
Found out it reads the card really slow.. That was why..

1. "0.3.3"
2. Windows 10 Pro
3. Yes
4. Yes, that was the one giving me the issue.

**Comment by boris-savic** [comment]
Ok. 

Follow the steps under Windows installation to disable Smart Card Plug & Play to speed up the card reading.
